#!/bin/bash
# index-knowledge.sh
# Generates an index of knowledge base files
#
# Usage: ./index-knowledge.sh [project-dir]
#   project-dir: Optional path to project root (default: current directory)
#
# Behavior:
#   - Scans .claude/memory/knowledge/ directory
#   - Reads first line (title) and first paragraph of each .md file
#   - Generates .claude/memory/knowledge/INDEX.md with table of contents
#
# Exit codes: 0 on success, 1 on error

set -e

# Get project directory (default to current)
PROJECT_DIR="${1:-.}"

# Resolve to absolute path
if command -v realpath &> /dev/null; then
    PROJECT_DIR=$(realpath "$PROJECT_DIR")
else
    PROJECT_DIR=$(cd "$PROJECT_DIR" && pwd)
fi

KNOWLEDGE_DIR="$PROJECT_DIR/.claude/memory/knowledge"
INDEX_FILE="$KNOWLEDGE_DIR/INDEX.md"

echo "Indexing knowledge base..."
echo "Knowledge directory: $KNOWLEDGE_DIR"
echo ""

# Check if knowledge directory exists
if [ ! -d "$KNOWLEDGE_DIR" ]; then
    echo "Knowledge directory does not exist. Creating it..."
    mkdir -p "$KNOWLEDGE_DIR"
fi

# Start building index content
current_date=$(date +"%Y-%m-%d %H:%M")

index_content="# Knowledge Base Index

**Generated**: $current_date

This index is auto-generated by \`index-knowledge.sh\`. Do not edit manually.

---

## Topics

"

# Count files for summary
file_count=0
entries=""

# Process each markdown file (excluding INDEX.md)
for file in "$KNOWLEDGE_DIR"/*.md; do
    # Check if glob matched any files
    [ -e "$file" ] || continue

    filename=$(basename "$file")

    # Skip INDEX.md and .gitkeep
    if [[ "$filename" == "INDEX.md" ]] || [[ "$filename" == ".gitkeep" ]]; then
        continue
    fi

    ((file_count++)) || true

    # Get the title (first line, strip markdown header prefix)
    title=$(head -n 1 "$file" | sed 's/^#* *//')
    if [ -z "$title" ]; then
        title="$filename"
    fi

    # Get first paragraph (skip title, find first non-empty paragraph)
    description=""
    in_paragraph=false
    while IFS= read -r line; do
        # Skip empty lines before first paragraph
        if [ -z "$line" ] && [ "$in_paragraph" = false ]; then
            continue
        fi

        # Skip the title line
        if [[ "$line" =~ ^#+ ]]; then
            continue
        fi

        # Start of paragraph
        if [ -n "$line" ]; then
            in_paragraph=true
            description="$description $line"
        fi

        # End of paragraph (empty line after content)
        if [ -z "$line" ] && [ "$in_paragraph" = true ]; then
            break
        fi
    done < "$file"

    # Trim whitespace and truncate description
    description=$(echo "$description" | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')
    if [ ${#description} -gt 200 ]; then
        description="${description:0:197}..."
    fi

    # Get last modified date
    if [[ "$OSTYPE" == "darwin"* ]]; then
        # macOS
        modified=$(stat -f "%Sm" -t "%Y-%m-%d" "$file")
    else
        # Linux
        modified=$(stat -c "%y" "$file" | cut -d' ' -f1)
    fi

    # Add entry
    entries="$entries### [$title]($filename)

$description

*Last modified: $modified*

---

"

done

# Finalize index content
if [ $file_count -eq 0 ]; then
    index_content="$index_content*No knowledge files found.*

Add markdown files to this directory to build your knowledge base.
"
else
    index_content="$index_content**Total topics: $file_count**

---

$entries"
fi

# Write index file
echo "$index_content" > "$INDEX_FILE"

echo "=== Index Generation Complete ==="
echo "Files indexed: $file_count"
echo "Index file: $INDEX_FILE"
