# index-knowledge.ps1
# Generates an index of knowledge base files
#
# Usage: .\index-knowledge.ps1 [-ProjectDir <path>]
#   -ProjectDir: Optional path to project root (default: current directory)
#
# Behavior:
#   - Scans .claude/memory/knowledge/ directory
#   - Reads first line (title) and first paragraph of each .md file
#   - Generates .claude/memory/knowledge/INDEX.md with table of contents
#
# Exit codes: 0 on success, 1 on error

param(
    [string]$ProjectDir = "."
)

# Resolve to absolute path
try {
    $ProjectDir = Resolve-Path $ProjectDir -ErrorAction Stop
} catch {
    Write-Error "Project directory not found: $ProjectDir"
    exit 1
}

$KnowledgeDir = Join-Path $ProjectDir ".claude\memory\knowledge"
$IndexFile = Join-Path $KnowledgeDir "INDEX.md"

Write-Host "Indexing knowledge base..." -ForegroundColor Cyan
Write-Host "Knowledge directory: $KnowledgeDir"
Write-Host ""

# Check if knowledge directory exists
if (-not (Test-Path $KnowledgeDir)) {
    Write-Host "Knowledge directory does not exist. Creating it..." -ForegroundColor Yellow
    New-Item -ItemType Directory -Path $KnowledgeDir -Force | Out-Null
}

# Start building index content
$currentDate = Get-Date -Format "yyyy-MM-dd HH:mm"

$indexContent = @"
# Knowledge Base Index

**Generated**: $currentDate

This index is auto-generated by ``index-knowledge.ps1``. Do not edit manually.

---

## Topics

"@

# Get all markdown files (excluding INDEX.md)
$knowledgeFiles = Get-ChildItem -Path $KnowledgeDir -Filter "*.md" -File -ErrorAction SilentlyContinue |
    Where-Object { $_.Name -ne "INDEX.md" }

$fileCount = 0
$entries = ""

foreach ($file in $knowledgeFiles) {
    $fileCount++

    # Read file content
    $content = Get-Content -Path $file.FullName -Raw -ErrorAction SilentlyContinue
    if (-not $content) {
        continue
    }

    $lines = $content -split "`n"

    # Get title (first line, strip markdown header prefix)
    $title = $lines[0] -replace '^#+\s*', ''
    if ([string]::IsNullOrWhiteSpace($title)) {
        $title = $file.BaseName
    }

    # Get first paragraph (skip title line, find first non-empty content block)
    $description = ""
    $inParagraph = $false
    $skipFirst = $true

    foreach ($line in $lines) {
        $trimmedLine = $line.Trim()

        # Skip the title line
        if ($skipFirst -and $trimmedLine -match '^#+') {
            $skipFirst = $false
            continue
        }
        $skipFirst = $false

        # Skip empty lines before first paragraph
        if ([string]::IsNullOrWhiteSpace($trimmedLine) -and -not $inParagraph) {
            continue
        }

        # Skip header lines
        if ($trimmedLine -match '^#+') {
            continue
        }

        # Start of paragraph
        if (-not [string]::IsNullOrWhiteSpace($trimmedLine)) {
            $inParagraph = $true
            $description += " $trimmedLine"
        }

        # End of paragraph (empty line after content)
        if ([string]::IsNullOrWhiteSpace($trimmedLine) -and $inParagraph) {
            break
        }
    }

    # Trim and truncate description
    $description = $description.Trim()
    if ($description.Length -gt 200) {
        $description = $description.Substring(0, 197) + "..."
    }

    # Get last modified date
    $modified = $file.LastWriteTime.ToString("yyyy-MM-dd")

    # Add entry
    $entries += @"

### [$title]($($file.Name))

$description

*Last modified: $modified*

---
"@
}

# Finalize index content
if ($fileCount -eq 0) {
    $indexContent += @"

*No knowledge files found.*

Add markdown files to this directory to build your knowledge base.
"@
} else {
    $indexContent += @"

**Total topics: $fileCount**

---
$entries
"@
}

# Write index file
$indexContent | Out-File -FilePath $IndexFile -Encoding utf8 -Force

Write-Host ""
Write-Host "=== Index Generation Complete ===" -ForegroundColor Cyan
Write-Host "Files indexed: $fileCount"
Write-Host "Index file: $IndexFile"
